### ISSUE TITLE
Uninitialized variable in rarely executed code path

### ISSUE THREAD

**Issue by hurufu** [skarnet/s6-networking#2]
Hello, 

Thanks for a very useful set of programs.
The rarely used IDENT protocol isn't correctly handled in `s6-tcpclient`, because of uninitialized `len` variable. Should I create a PR for it? The fix is trivial:

```diff
--- a/src/libs6net/s6net_ident_reply_get.c	2023-01-23 01:50:12.066973124 +0100
+++ b/src/libs6net/s6net_ident_reply_get.c	2023-01-23 01:50:28.143873049 +0100
@@ -12,11 +12,11 @@
 
 #include <s6-networking/ident.h>
 
 ssize_t s6net_ident_reply_get (char *s, ip46 const *remoteip, uint16_t remoteport, ip46 const *localip, uint16_t localport, tain const *deadline, tain *stamp)
 {
-  size_t len ;
+  size_t len = 0 ;
   int fd ;
   if (ip46_is6(remoteip) != ip46_is6(localip)) return (errno = EAFNOSUPPORT, -1) ;
   fd = socket_tcp46(ip46_is6(remoteip)) ;
   if (fd < 0) return -1 ;
   if (socket_bind46(fd, localip, 0) < 0) goto err ;
```

**Comment by skarnet** [comment]
Indeed. Usually compilers warn of uninitialized variables, but not this one, because it's passed by reference to a function in a different TU - and it's okay for output parameters, but here it's an input+output parameter so it does need to be initialized.

Thanks for the report! Fixed in git, numbered release coming at some point in the future.
